# Fasz kivan

In [17]:
import pandas as pd
import numpy as np

local_path = '/Users/csizi/Development/marathon_statistics/dataset/csv/bszm_2008_2020/'

bszm = pd.read_csv(local_path + 'bszm_cleaned.csv', encoding = "utf8", 
                    sep=';', header=0)

In [18]:
bszm.drop(['Category/Placement', 'event_year', '1.day/1.length', '1.day/2.length', '1.day/3.length', '1.day/length', '2.day/1.length', '2.day/2.length', '2.day/3.length', '2.day/length',
           '3.day/1.length', '3.day/2.length', '3.day/3.length', '3.day/length', '4.day/1.length', '4.day/2.length', '4.day/3.length', '4.day/length', 'event_length'], axis = 1, inplace=True)

In [19]:
bszm.drop(['Name', 'Placement', 'Born', 'Team', 'City', 'Number', '1.day/1.time', '1.day/2.time', '1.day/3.time', '1.day/sum', '2.day/1.time'
           , '2.day/2.time', '2.day/3.time', '2.day/sum', '3.day/1.time', '3.day/2.time', '3.day/3.time', '3.day/sum', '4.day/1.time', '4.day/2.time'
           , '4.day/3.time', '4.day/sum', 'Category', 'Country', 'tempo_category'], axis = 1, inplace=True)

In [22]:
bszm['Gender'] = pd.get_dummies(bszm['Gender'], drop_first=True)
bszm['finished'] = pd.get_dummies(bszm['finished'], drop_first=True)
bszm['club_member'] = pd.get_dummies(bszm['club_member'], drop_first=True)

In [23]:
import tensorflow as tf
print(tf.__version__)

2.8.0

In [24]:
bszm

,Gender,Result,Ran km,finished,age,finisher_result,average_tempo(minutes/km),1/1_tempo,1/2_tempo,1/3_tempo,...,2_tempo,3/1_tempo,3/2_tempo,3/3_tempo,3_tempo,4/1_tempo,4/2_tempo,4/3_tempo,4_tempo,club_member
0,1,46928.0,196.0,1,43.0,46928.0,3.990476,4.277778,3.839506,4.087992,...,3.979836,3.962406,4.100000,3.931298,4.006912,3.833333,4.529304,3.649123,4.016346,1
1,1,47208.0,196.0,1,32.0,47208.0,4.014286,4.270833,3.845679,4.410973,...,4.165721,3.705514,3.980392,3.924936,3.879416,3.693613,4.411172,3.634503,3.925321,1
2,1,50735.0,196.0,1,38.0,50735.0,4.314201,4.572917,0.000000,8.600414,...,4.417769,4.223058,4.362745,4.145038,4.254224,4.154691,4.875458,3.846979,4.305769,1
3,1,51767.0,196.0,1,34.0,51767.0,4.401956,4.791667,4.250000,4.585921,...,4.525520,4.219298,4.365686,4.229008,4.279570,4.171657,4.877289,3.949318,4.345513,0
4,1,52959.0,196.0,1,42.0,52959.0,4.503316,4.686343,4.277778,4.641822,...,4.546314,4.478697,4.529412,4.655216,4.540323,4.280439,5.017399,4.139376,4.491987,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2501,1,84831.0,195.0,1,43.0,84831.0,7.250513,6.629630,7.161523,7.945135,...,7.445810,6.912281,6.961765,7.399491,7.078725,6.743513,7.088828,7.702729,7.179808,0
2502,0,85191.0,195.0,1,42.0,85191.0,7.281282,5.500000,5.692387,6.379917,...,7.097669,6.694236,8.759804,9.022901,8.206221,6.975050,8.449634,8.411306,7.963462,1
2503,1,85541.0,195.0,1,45.0,85541.0,7.311197,6.024306,6.377572,8.327122,...,7.248897,6.674185,7.541176,8.452926,7.550691,6.670659,7.947802,7.855750,7.507372,0
2504,0,87555.0,195.0,1,24.0,87555.0,7.483333,5.578704,6.702675,7.359213,...,7.643352,6.308271,8.311765,8.634860,7.795315,6.602794,7.958791,9.010721,7.869231,0
2505,1,88516.0,195.0,1,59.0,88516.0,7.565470,6.578704,7.193416,7.927536,...,7.584121,6.909774,0.000000,17.515267,7.404378,7.044910,8.463370,8.311891,7.958013,1

In [27]:
x = bszm
y = bszm['finished']
x.drop(['finished'], axis = 1, inplace=True)
x

,Gender,Result,Ran km,age,finisher_result,average_tempo(minutes/km),1/1_tempo,1/2_tempo,1/3_tempo,1_tempo,...,2_tempo,3/1_tempo,3/2_tempo,3/3_tempo,3_tempo,4/1_tempo,4/2_tempo,4/3_tempo,4_tempo,club_member
0,1,46928.0,196.0,43.0,46928.0,3.990476,4.277778,3.839506,4.087992,4.043897,...,3.979836,3.962406,4.100000,3.931298,4.006912,3.833333,4.529304,3.649123,4.016346,1
1,1,47208.0,196.0,32.0,47208.0,4.014286,4.270833,3.845679,4.410973,4.153105,...,4.165721,3.705514,3.980392,3.924936,3.879416,3.693613,4.411172,3.634503,3.925321,1
2,1,50735.0,196.0,38.0,50735.0,4.314201,4.572917,0.000000,8.600414,4.354390,...,4.417769,4.223058,4.362745,4.145038,4.254224,4.154691,4.875458,3.846979,4.305769,1
3,1,51767.0,196.0,34.0,51767.0,4.401956,4.791667,4.250000,4.585921,4.532834,...,4.525520,4.219298,4.365686,4.229008,4.279570,4.171657,4.877289,3.949318,4.345513,0
4,1,52959.0,196.0,42.0,52959.0,4.503316,4.686343,4.277778,4.641822,4.529265,...,4.546314,4.478697,4.529412,4.655216,4.540323,4.280439,5.017399,4.139376,4.491987,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2501,1,84831.0,195.0,43.0,84831.0,7.250513,6.629630,7.161523,7.945135,7.267666,...,7.445810,6.912281,6.961765,7.399491,7.078725,6.743513,7.088828,7.702729,7.179808,0
2502,0,85191.0,195.0,42.0,85191.0,7.281282,5.500000,5.692387,6.379917,5.870093,...,7.097669,6.694236,8.759804,9.022901,8.206221,6.975050,8.449634,8.411306,7.963462,1
2503,1,85541.0,195.0,45.0,85541.0,7.311197,6.024306,6.377572,8.327122,6.940757,...,7.248897,6.674185,7.541176,8.452926,7.550691,6.670659,7.947802,7.855750,7.507372,0
2504,0,87555.0,195.0,24.0,87555.0,7.483333,5.578704,6.702675,7.359213,6.582441,...,7.643352,6.308271,8.311765,8.634860,7.795315,6.602794,7.958791,9.010721,7.869231,0
2505,1,88516.0,195.0,59.0,88516.0,7.565470,6.578704,7.193416,7.927536,7.256959,...,7.584121,6.909774,0.000000,17.515267,7.404378,7.044910,8.463370,8.311891,7.958013,1

In [28]:
tf.random.set_seed(42)

In [29]:
model_1 = tf.keras.Sequential([tf.keras.layers.Dense(1)])

2022-04-05 20:44:50.134804: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [30]:
x = np.asarray(x).astype('float32')

In [31]:
model_1.compile(loss = tf.keras.losses.BinaryCrossentropy(), optimizer = tf.keras.optimizers.SGD(), metrics = ['accuracy'])
#SGD stands for Stochastic Gradient Descent

model_1.fit(x, y, epochs = 200)

Epoch 1/10
79/79 [==============================] - 0s 858us/step - loss: nan - accuracy: 0.1081
Epoch 2/10
79/79 [==============================] - 0s 820us/step - loss: nan - accuracy: 0.1081
Epoch 3/10
79/79 [==============================] - 0s 807us/step - loss: nan - accuracy: 0.1081
Epoch 4/10
79/79 [==============================] - 0s 930us/step - loss: nan - accuracy: 0.1081
Epoch 5/10
79/79 [==============================] - 0s 954us/step - loss: nan - accuracy: 0.1081
Epoch 6/10
79/79 [==============================] - 0s 889us/step - loss: nan - accuracy: 0.1081
Epoch 7/10
79/79 [==============================] - 0s 911us/step - loss: nan - accuracy: 0.1081
Epoch 8/10
79/79 [==============================] - 0s 866us/step - loss: nan - accuracy: 0.1081
Epoch 9/10
79/79 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.1081
Epoch 10/10
79/79 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.1081